/** Illustrative collection totals for globe labels — all 50 U.S. states. */
export type UsStateCollection = {
  name: string;
  abbr: string;
  amt: string;
};

export const US_STATE_COLLECTIONS: UsStateCollection[] = [
  { name: 'Alabama', abbr: 'AL', amt: '$430K' },
  { name: 'Alaska', abbr: 'AK', amt: '$180K' },
  { name: 'Arizona', abbr: 'AZ', amt: '$920K' },
  { name: 'Arkansas', abbr: 'AR', amt: '$240K' },
  { name: 'California', abbr: 'CA', amt: '$4.2M' },
  { name: 'Colorado', abbr: 'CO', amt: '$580K' },
  { name: 'Connecticut', abbr: 'CT', amt: '$320K' },
  { name: 'Delaware', abbr: 'DE', amt: '$210K' },
  { name: 'Florida', abbr: 'FL', amt: '$2.8M' },
  { name: 'Georgia', abbr: 'GA', amt: '$1.6M' },
  { name: 'Hawaii', abbr: 'HI', amt: '$290K' },
  { name: 'Idaho', abbr: 'ID', amt: '$250K' },
  { name: 'Illinois', abbr: 'IL', amt: '$1.9M' },
  { name: 'Indiana', abbr: 'IN', amt: '$640K' },
  { name: 'Iowa', abbr: 'IA', amt: '$260K' },
  { name: 'Kansas', abbr: 'KS', amt: '$220K' },
  { name: 'Kentucky', abbr: 'KY', amt: '$380K' },
  { name: 'Louisiana', abbr: 'LA', amt: '$400K' },
  { name: 'Maine', abbr: 'ME', amt: '$230K' },
  { name: 'Maryland', abbr: 'MD', amt: '$610K' },
  { name: 'Massachusetts', abbr: 'MA', amt: '$720K' },
  { name: 'Michigan', abbr: 'MI', amt: '$980K' },
  { name: 'Minnesota', abbr: 'MN', amt: '$550K' },
  { name: 'Mississippi', abbr: 'MS', amt: '$270K' },
  { name: 'Missouri', abbr: 'MO', amt: '$520K' },
  { name: 'Montana', abbr: 'MT', amt: '$190K' },
  { name: 'Nebraska', abbr: 'NE', amt: '$310K' },
  { name: 'Nevada', abbr: 'NV', amt: '$280K' },
  { name: 'New Hampshire', abbr: 'NH', amt: '$240K' },
  { name: 'New Jersey', abbr: 'NJ', amt: '$870K' },
  { name: 'New Mexico', abbr: 'NM', amt: '$330K' },
  { name: 'New York', abbr: 'NY', amt: '$2.5M' },
  { name: 'North Carolina', abbr: 'NC', amt: '$1.1M' },
  { name: 'North Dakota', abbr: 'ND', amt: '$170K' },
  { name: 'Ohio', abbr: 'OH', amt: '$1.2M' },
  { name: 'Oklahoma', abbr: 'OK', amt: '$340K' },
  { name: 'Oregon', abbr: 'OR', amt: '$360K' },
  { name: 'Pennsylvania', abbr: 'PA', amt: '$1.4M' },
  { name: 'Rhode Island', abbr: 'RI', amt: '$200K' },
  { name: 'South Carolina', abbr: 'SC', amt: '$460K' },
  { name: 'South Dakota', abbr: 'SD', amt: '$185K' },
  { name: 'Tennessee', abbr: 'TN', amt: '$690K' },
  { name: 'Texas', abbr: 'TX', amt: '$3.1M' },
  { name: 'Utah', abbr: 'UT', amt: '$300K' },
  { name: 'Vermont', abbr: 'VT', amt: '$195K' },
  { name: 'Virginia', abbr: 'VA', amt: '$810K' },
  { name: 'Washington', abbr: 'WA', amt: '$760K' },
  { name: 'West Virginia', abbr: 'WV', amt: '$260K' },
  { name: 'Wisconsin', abbr: 'WI', amt: '$490K' },
  { name: 'Wyoming', abbr: 'WY', amt: '$165K' },
];
